In [117]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, r2_score, f1_score
from sklearn.svm import SVC
from tqdm import tqdm
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.pipeline import Pipeline

In [118]:
df = pd.read_csv('Glass.csv')
df

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,Type
0,1.52101,13.64,4.49,1.10,71.78,0.06,8.75,0.00,0.0,building_windows_float_processed
1,1.51761,13.89,3.60,1.36,72.73,0.48,7.83,0.00,0.0,building_windows_float_processed
2,1.51618,13.53,3.55,1.54,72.99,0.39,7.78,0.00,0.0,building_windows_float_processed
3,1.51766,13.21,3.69,1.29,72.61,0.57,8.22,0.00,0.0,building_windows_float_processed
4,1.51742,13.27,3.62,1.24,73.08,0.55,8.07,0.00,0.0,building_windows_float_processed
...,...,...,...,...,...,...,...,...,...,...
209,1.51623,14.14,0.00,2.88,72.61,0.08,9.18,1.06,0.0,headlamps
210,1.51685,14.92,0.00,1.99,73.06,0.00,8.40,1.59,0.0,headlamps
211,1.52065,14.36,0.00,2.02,73.42,0.00,8.44,1.64,0.0,headlamps
212,1.51651,14.38,0.00,1.94,73.61,0.00,8.48,1.57,0.0,headlamps
213,1.51711,14.23,0.00,2.08,73.36,0.00,8.62,1.67,0.0,headlamps

In [119]:
X = df.drop('Type', axis=1)
y = df['Type']

In [120]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=24, stratify=y)

In [121]:
scaler = StandardScaler()

Cs = np.linspace(0.001, 4, 10)

DF = ['ovo', 'ovr']
scores = []


for i in tqdm(range(len(Cs))):
    for j in DF:
        svm = SVC(kernel='linear', C = Cs[i], decision_function_shape=j)
        pipe = Pipeline([('Scaler', scaler) , ('SVM',svm )])
        pipe.fit(X_train, y_train)
        y_pred = pipe.predict(X_test)
        scores.append([Cs[i], j, accuracy_score(y_test, y_pred)])

print(scores)

df1 = pd.DataFrame(scores , columns=['C', 'degree', 'F1'])
df1.sort_values('F1',ascending=False ).iloc[0]

100%|█████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 104.42it/s]

[[0.001, 'ovo', 0.35384615384615387], [0.001, 'ovr', 0.35384615384615387], [0.44533333333333336, 'ovo', 0.5846153846153846], [0.44533333333333336, 'ovr', 0.5846153846153846], [0.8896666666666667, 'ovo', 0.6], [0.8896666666666667, 'ovr', 0.6], [1.334, 'ovo', 0.6307692307692307], [1.334, 'ovr', 0.6307692307692307], [1.7783333333333333, 'ovo', 0.6307692307692307], [1.7783333333333333, 'ovr', 0.6307692307692307], [2.2226666666666666, 'ovo', 0.6153846153846154], [2.2226666666666666, 'ovr', 0.6153846153846154], [2.6670000000000003, 'ovo', 0.6307692307692307], [2.6670000000000003, 'ovr', 0.6307692307692307], [3.1113333333333335, 'ovo', 0.6307692307692307], [3.1113333333333335, 'ovr', 0.6307692307692307], [3.5556666666666668, 'ovo', 0.6307692307692307], [3.5556666666666668, 'ovr', 0.6307692307692307], [4.0, 'ovo', 0.6307692307692307], [4.0, 'ovr', 0.6307692307692307]]

C              4.0
degree         ovr
F1        0.630769
Name: 19, dtype: object

# For Image Segmentation Dataset

In [123]:
df = pd.read_csv('Image_Segmentation.csv')

In [124]:
df

,Class,region.centroid.col,region.centroid.row,region.pixel.count,short.line.density.5,short.line.density.2,vedge.mean,vegde.sd,hedge.mean,hedge.sd,intensity.mean,rawred.mean,rawblue.mean,rawgreen.mean,exred.mean,exblue.mean,exgreen.mean,value.mean,saturation.mean,hue-mean
0,BRICKFACE,188,133,9,0.000000,0.0,0.333333,0.266667,0.500000,0.077778,6.666666,8.333334,7.777778,3.888889,5.000000,3.333333,-8.333333,8.444445,0.538580,-0.924817
1,BRICKFACE,105,139,9,0.000000,0.0,0.277778,0.107407,0.833333,0.522222,6.111111,7.555555,7.222222,3.555556,4.333334,3.333333,-7.666666,7.555555,0.532628,-0.965946
2,BRICKFACE,34,137,9,0.000000,0.0,0.500000,0.166667,1.111111,0.474074,5.851852,7.777778,6.444445,3.333333,5.777778,1.777778,-7.555555,7.777778,0.573633,-0.744272
3,BRICKFACE,39,111,9,0.000000,0.0,0.722222,0.374074,0.888889,0.429629,6.037037,7.000000,7.666666,3.444444,2.888889,4.888889,-7.777778,7.888889,0.562919,-1.175773
4,BRICKFACE,16,128,9,0.000000,0.0,0.500000,0.077778,0.666667,0.311111,5.555555,6.888889,6.666666,3.111111,4.000000,3.333333,-7.333334,7.111111,0.561508,-0.985811
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,GRASS,36,243,9,0.111111,0.0,1.888889,1.851851,2.000000,0.711110,13.333333,9.888889,12.111111,18.000000,-10.333333,-3.666667,14.000000,18.000000,0.452229,2.368311
205,GRASS,186,218,9,0.000000,0.0,1.166667,0.744444,1.166667,0.655555,13.703704,10.666667,12.666667,17.777779,-9.111111,-3.111111,12.222222,17.777779,0.401347,2.382684
206,GRASS,197,236,9,0.000000,0.0,2.444444,6.829628,3.333333,7.599998,16.074074,13.111111,16.666668,18.444445,-8.888889,1.777778,7.111111,18.555555,0.292729,2.789800
207,GRASS,208,240,9,0.111111,0.0,1.055556,0.862963,2.444444,5.007407,14.148149,10.888889,13.000000,18.555555,-9.777778,-3.444444,13.222222,18.555555,0.421621,2.392487
208,GRASS,223,185,9,0.000000,0.0,0.500000,0.349603,2.388889,2.080776,12.962963,11.555555,9.777778,17.555555,-4.222222,-9.555555,13.777778,17.555555,0.445418,1.838850

In [125]:
X = df.drop('Class',axis = 1)
y = df['Class']

In [126]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=24, stratify=y)

In [151]:
#Using Gamma(Radial)

scaler = MinMaxScaler()

Cs = np.linspace(0.001, 4, 10)
Gs = np.linspace(0.001, 4, 10)
DF = ['ovo', 'ovr']
scores = []


for c in tqdm(range(len(Cs))):
    for d in DF:
        for g in Gs:
            svm = SVC(kernel='linear',C=Cs[c],decision_function_shape=d, gamma=g)
            pipe = Pipeline([('scale',scaler),('svm', svm)])
            pipe.fit(X_train,y_train)
            y_pred = pipe.predict(X_test)
            scores.append([Cs[c],d, g ,accuracy_score(y_test,y_pred)])

df1 = pd.DataFrame(scores , columns=['C', 'degree', 'Gamma' ,'accuracy'])
df1.sort_values('accuracy',ascending=False ).iloc[0]

100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 11.88it/s]

C                4.0
degree           ovr
Gamma            4.0
accuracy    0.857143
Name: 199, dtype: object

In [153]:
df1

         C degree     Gamma  accuracy
0    0.001    ovo  0.001000  0.666667
1    0.001    ovo  0.445333  0.666667
2    0.001    ovo  0.889667  0.666667
3    0.001    ovo  1.334000  0.666667
4    0.001    ovo  1.778333  0.666667
..     ...    ...       ...       ...
195  4.000    ovr  2.222667  0.857143
196  4.000    ovr  2.667000  0.857143
197  4.000    ovr  3.111333  0.857143
198  4.000    ovr  3.555667  0.857143
199  4.000    ovr  4.000000  0.857143

[200 rows x 4 columns]

In [128]:
# scaler = StandardScaler()

# Cs = np.linspace(0.001, 4, 10)

# DF = ['ovo', 'ovr']
# scores = []


# for c in tqdm(range(len(Cs))):
#     for d in DF:
#         svm = SVC(kernel='linear',C=Cs[c],decision_function_shape=d)
#         pipe = Pipeline([('scale',scaler),('svm', svm)])
#         pipe.fit(X_train,y_train)
#         y_pred = pipe.predict(X_test)
#         scores.append([Cs[c],d,accuracy_score(y_test,y_pred)])
           

# df1 = pd.DataFrame(scores , columns=['C', 'degree' ,'accuracy'])
# df1.sort_values('accuracy',ascending=False ).iloc[0]

100%|█████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 101.28it/s]

C                4.0
degree           ovr
accuracy    0.873016
Name: 19, dtype: object

Without Gamma(Radial) Accuracy is - 
C                4.0
degree           ovr
accuracy    0.873016
Name: 19, dtype: object