In [3]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import numpy as np
from sklearn.decomposition import PCA , KernelPCA
import os
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split ,StratifiedKFold , GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

In [9]:
df = pd.read_csv('milk.csv', index_col=0)

            water  protein   fat  lactose   ash
Animal
HORSE        90.1      2.6   1.0      6.9  0.35
ORANGUTAN    88.5      1.4   3.5      6.0  0.24
MONKEY       88.4      2.2   2.7      6.4  0.18
DONKEY       90.3      1.7   1.4      6.2  0.40
HIPPO        90.4      0.6   4.5      4.4  0.10
CAMEL        87.7      3.5   3.4      4.8  0.71
BISON        86.9      4.8   1.7      5.7  0.90
BUFFALO      82.1      5.9   7.9      4.7  0.78
GUINEA PIG   81.9      7.4   7.2      2.7  0.85
CAT          81.6     10.1   6.3      4.4  0.75
FOX          81.6      6.6   5.9      4.9  0.93
LLAMA        86.5      3.9   3.2      5.6  0.80
MULE         90.0      2.0   1.8      5.5  0.47
PIG          82.8      7.1   5.1      3.7  1.10
ZEBRA        86.2      3.0   4.8      5.3  0.70
SHEEP        82.0      5.6   6.4      4.7  0.91
DOG          76.3      9.3   9.5      3.0  1.20
ELEPHANT     70.7      3.6  17.6      5.6  0.63
RABBIT       71.3     12.3  13.1      1.9  2.30
RAT          72.5      9.2  12.6      3.3  1.40
DEER         65.9     10.4  19.7      2.6  1.40
REINDEER     64.8     10.7  20.3      2.5  1.40
WHALE        64.8     11.1  21.2      1.6  1.70
SEAL         46.4      9.7  42.0      0.0  0.85
DOLPHIN      44.9     10.6  34.9      0.9  0.53

In [15]:
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df)
pca = KernelPCA(kernel='linear').set_output(transform='pandas')
pca_data = pca.fit_transform(df_scaled)

    kernelpca0  kernelpca1  kernelpca2  kernelpca3  kernelpca4
0    -2.435175   -0.231478    0.330150    0.307664   -0.048184
1    -2.258736   -0.693148    0.029035   -0.081057    0.000532
2    -2.335861   -0.663328    0.101257    0.247997   -0.010109
3    -2.318677   -0.273815    0.109881   -0.092873    0.006769
4    -2.060294   -1.019199   -0.762436   -0.510091   -0.029382
5    -1.301536    0.137303   -0.198742   -0.282160    0.014668
6    -1.282742    0.622667    0.253785    0.065148    0.044486
7    -0.505068    0.088235    0.008383    0.133774   -0.083806
8     0.255502    0.287373   -0.881857   -0.013100    0.016484
9     0.051008    0.470136   -0.355676    1.050970   -0.159793
10   -0.429017    0.459312    0.135181    0.236941    0.024309
11   -1.364034    0.309224    0.228597   -0.088242    0.024345
12   -2.012658   -0.192807   -0.131325   -0.242899    0.025286
13    0.000100    0.788138   -0.334070   -0.056860    0.056423
14   -1.390928   -0.012660    0.116929   -0.287079    0.004502
15   -0.513120    0.321365    0.078943   -0.020171    0.035616
16    0.982829    0.725239   -0.331552    0.169590    0.063456
17   -0.302294   -1.079878    1.004594   -0.114093   -0.000905
18    2.798474    2.288793    0.161914   -0.394421    0.021719
19    1.309609    0.774032    0.159709    0.015485    0.064371
20    2.212053    0.345036    0.211472    0.064829   -0.044332
21    2.345616    0.310003    0.205686    0.108605   -0.031051
22    2.892787    0.721121    0.055943   -0.276172   -0.054319
23    4.133773   -2.200801   -0.067215   -0.374615   -0.190501
24    3.528390   -2.280863   -0.128585    0.432830    0.249417